trigger:
- main

pool: Default # Agent is running on a machine on prem 

variables:
  HTTP_PROXY: "http://127.0.0.1:8888"
  HTTPS_PROXY: "http://127.0.0.1:8888"   # use http:// even for HTTPS proxy values (common convention)
  NO_PROXY: "127.0.0.1,localhost,::1"
  system.debug: true
  JFROG_CLI_LOG_LEVEL: DEBUG


stages:
  - stage: 'DownloadAndPublish'
    displayName: 'Download, push and update unified agent'
    jobs:
    - job: 'DownloadAndPublish'
      steps:      
      - task: JfrogCliV2@1
        name: jfStep
        inputs:
          jfrogPlatformConnection: 'JFrog Platform connexion'
          command: |            
            jf rt ping
        continueOnError: true
